services:
  - postgresql
dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "9.5"
  code_climate:
        repo_token:
          secure: "db3d67198bc95a577c6ba82351ae6c4167a45b070acd20da99cc9373c97331e1"
before_script:
  - travis_wait npm install
  - npm install codeclimate-test-reporter -g
script:
  - ./node_modules/mocha/bin/mocha --recursive './test/' --compilers js:babel-core/register --exit
after_success:
  - npm run cover
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
